[DPE-3006] Add initial snap
canonical/charmed-karapace-snap pull request #1
Opened 2024-04-12 09:14 UTC by zmraul

Adds initial snap with a Karapace installation.

Creates two apps:
- `daemon`:  main service, will need correct `karapace.config.json` and `authfile.json` to work properly
- `mkpasswd`: tool to create passwords that will follow the convention on authfile.json.

2024-04-12 14:36 UTC, deusebio requested changes
Looks good! I only have one major comment I'd like to address (tagged with **issue**). All the rest are nipticks

2024-04-12 14:36 UTC, deusebio commented on snap/snapcraft.yaml
> +    source: https://github.com/Aiven-Open/karapace.git  # pip install git+https://github.com/Aiven-Open/karapace@main
**issue** we should probably pin this, and not just use the repository. We could actually use the tags (I checked upstream repo, and they do have tags for their releases), just to control and trace a bit better what we are installing. Otherwise it is hard to make sure that the version we define in the snap (`version` field above) correspond to what we are installing.

2024-04-12 14:36 UTC, deusebio commented on snap/hooks/install
> +export LOG="${SNAP_COMMON}"/var/log/$COMPONENT
**question** Just for my understanding, how can we make sure that the logs are stored here?

2024-04-12 14:36 UTC, deusebio commented on snap/snapcraft.yaml
> +    command: bin/karapace_mkpasswd
**question** I'm not sure I was able to understand where this file comes from? Is it installed with the pip install command?

2024-04-12 14:36 UTC, deusebio commented on snap/snapcraft.yaml
> +    command: /opt/karapace/bin/start-wrapper.bash
uhm, maybe it should be 

```suggestion
    command: opt/karapace/bin/start-wrapper.bash
```

I was comparing this with the `mkpasswd` and the `charmed-kafka-snap`? Does this work anyway? Anyhow, it is a small point but maybe it is better to keep consistency

2024-04-12 14:41 UTC, zmraul commented on snap/snapcraft.yaml
> +    command: bin/karapace_mkpasswd
Yes, it's installed on `bin` as part of the internal pyhton venv. Same for the main `karapace` entrypoint.

2024-04-12 14:47 UTC, zmraul commented on snap/snapcraft.yaml
> +    command: /opt/karapace/bin/start-wrapper.bash
My guess it's that the snap only sees the internal filesystem when executing commands, unless given permission through plugs. But I agree it should have the same pattern.

2024-04-12 14:48 UTC, zmraul commented on snap/hooks/install
> +export LOG="${SNAP_COMMON}"/var/log/$COMPONENT
We don't at the moment. Logs are not stored anywhere other than the normal systemd service logs. I left it there and had COS plug commented out while I figure out if they can be extracted into a file.

2024-04-12 15:31 UTC, deusebio commented on snap/hooks/install
> +export LOG="${SNAP_COMMON}"/var/log/$COMPONENT
All right! That's fine!

2024-04-15 08:15 UTC, zmraul commented
Added `publish.yaml` workflow. No check on branch & metadata consistency, as branches on GH and snapstore are not following a release pattern yet.

2024-04-15 19:57 UTC, deusebio approved these changes
Looks good! Please just test the suggestion I provide below. If there is no easy way to make it work easily, that's all right, let's skip this. But it would be worth the shot, just to prevent possible bugs.

2024-04-15 19:57 UTC, deusebio commented on snap/snapcraft.yaml
> +    source-tag: 3.12.0
That's interesting! I did not know that this key existed. TIL! :D 

Could we just try to use `${SNAPCRAFT_PROJECT_VERSION}` as [here](https://github.com/canonical/charmed-kafka-snap/blob/3/edge/snap/snapcraft.yaml#L233). If that would work, it would centralize this changes into a single line and avoid making mistake.

2024-04-16 11:28 UTC, zmraul commented on snap/snapcraft.yaml
> +    source-tag: 3.12.0
Yes, you can specify `source-branch`, `source-commit` and many other things. ([search for `source-`](https://snapcraft.io/docs/snapcraft-yaml-reference))

2024-04-17 14:43 UTC, marcoppenheimer approved these changes

2024-04-17 14:43 UTC, marcoppenheimer commented on snap/snapcraft.yaml
> +    command: bin/karapace_mkpasswd
**question:** What does `mkpasswd` do? I'm sure it makes passwords, but curious for a deeper explanation.

2024-04-17 14:43 UTC, marcoppenheimer commented on snap/snapcraft.yaml
> +    source: https://github.com/Aiven-Open/karapace.git  # pip install git+https://github.com/Aiven-Open/karapace@main
@zmraul - Did this get addressed with `source-tag`?

2024-04-18 07:24 UTC, zmraul commented on snap/snapcraft.yaml
> +    source: https://github.com/Aiven-Open/karapace.git  # pip install git+https://github.com/Aiven-Open/karapace@main
yes

2024-04-18 08:02 UTC, zmraul commented on snap/snapcraft.yaml
> +    command: bin/karapace_mkpasswd
I _really_ just makes a password, not even registers it anywhere, just returns a string with json format so you have to manually add it to the file.
1) [entrypoint of mk_passwd](https://github.com/Aiven-Open/karapace/blob/main/karapace/auth.py#L257-L275)
2) The [function that creates the password](https://github.com/Aiven-Open/karapace/blob/main/karapace/auth.py#L47-L59). Literally our `workload.generate_password()` but with extra options. :upside_down_face:

2024-04-18 08:03 UTC, zmraul commented on .github/workflows/ci.yaml
> +          sudo DEBIAN_FRONTEND=noninteractive apt upgrade --yes
We don't. I removed it. Thanks!

2024-04-18 08:07 UTC, merged